version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_CRON_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
