name: Docker Build and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

permissions:
  contents: read
  packages: write

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for new postgres:16 image
        id: check-postgres
        run: |
          latest_digest=$(docker pull postgres:16 > /dev/null && docker inspect --format='{{index .RepoDigests 0}}' postgres:16)
          echo "LATEST_DIGEST=$latest_digest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            POSTGRES_DIGEST=${{ steps.check-postgres.outputs.LATEST_DIGEST }}
